python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 10 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 20 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 30 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 40 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/contact/network.hyp --algorithm ks --k 50 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 10 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 20 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 30 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 40 --s 4.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 0.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 1.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 2.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 3.5 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.0 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.0 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.0 --c 1.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.5 --c 0.5 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.5 --c 1.0 &&
python3 main.py --network ./datasets/real/congress/network.hyp --algorithm ks --k 50 --s 4.5 --c 1.5